/*
 * arduino_inference.h — AUTO-GENERATED by src/train_tinyml.py
 * DO NOT EDIT MANUALLY. Re-run train_tinyml.py to regenerate.
 *
 * Model   : SGDClassifier(loss=log_loss, penalty=l1)
 * Features: 5 EEG band-power scalars (Delta, Theta, Alpha, Beta, Gamma)
 * Classes : calm (0), relaxed (1), stressed (2)
 * Accuracy: 74.0% on 20% held-out test set
 *
 * ARM NOTE: On Cortex-M4F (R4 Minima), double is 8 bytes and float is 4 bytes.
 *   score() uses double types for compatibility with arduinoFFT v1.9.x.
 *   const data is stored in flash automatically — no PROGMEM needed.
 *
 * C++ NOTE: score() is written without C99 compound literals so it
 *   compiles cleanly under C++11 (used by the Arduino IDE for .ino files).
 *
 * Validation vector: raw_input=[0.5,0.5,0.5,0.5,0.5]
 *   Expected prediction_id : 2  (stressed)
 *   Expected confidence    : 1.0000
 *   (Note: 0.5 raw input is an extreme outlier above the training
 *    distribution — scaler maps it to large positive values.
 *    This is correct behaviour; verify with realistic EEG inputs.)
 */

#pragma once

/* Scaler parameters (const → stored in flash on ARM). Applied before score(). */
/* Formula: scaled[i] = (raw[i] - BAND_SCALER_MEAN[i]) / BAND_SCALER_SCALE[i] */
static const float BAND_SCALER_MEAN[5]  = { 0.09183148f, 0.04502182f, 0.02965970f, 0.01678868f, 0.01046119f };
static const float BAND_SCALER_SCALE[5] = { 0.04006524f, 0.02089566f, 0.01705777f, 0.00745868f, 0.00419869f };

/* Class label lookup (index = prediction_id from argmax of score output) */
static const char* const PRED_CLASSES[3] = { "calm", "relaxed", "stressed" };

/* score(): OvR linear decision function (m2cgen-equivalent, C++11 safe)
 *   input  - pointer to 5 z-scored band-power features
 *   output - pointer to 3 doubles; argmax gives the predicted class id
 *            Apply softmax to output[0..2] for calibrated probabilities. */
void score(double* input, double* output) {
    output[0] = -0.8665357790940681 + input[0] * -0.3086582691282320 + input[1] * -0.9204997154762579 + input[2] * 3.1180629958968189 + input[3] * 0.5534958380362084 + input[4] * -1.1155842068085007;
    output[1] = -1.0337644461390918 + input[0] * 0.2494096568419120 + input[1] * 1.0212753392293494 + input[2] * -1.2946316845847550 + input[3] * 0.8194574241428491 + input[4] * -0.5320899552614659;
    output[2] = -2.5309764820771616 + input[0] * -0.5980654187316252 + input[2] * -4.0759279986071490 + input[3] * -2.4170512937524560 + input[4] * 2.4027266702976320;
}
