/*
 * mindtune_edge.ino — MindTune-OS Edge Inference Sketch
 *
 * In plain English: this sketch turns an Arduino Uno into a real-time EEG
 * stress detector. It samples the analog EEG signal 256 times per second,
 * converts 128 consecutive samples into frequency content using a Fast Fourier
 * Transform (FFT), sums that frequency content into 5 brainwave bands, runs
 * those 5 numbers through the trained classifier, and transmits the result
 * over Serial — one classification every 0.5 seconds.
 *
 * Hardware : BioAmp EXG Pill (1-channel EEG) on Analog Pin A0
 *            Arduino Uno R4 Minima (Renesas RA4M1, Cortex-M4F, 48 MHz, 32 KB SRAM)
 *            Power EXG Pill from 5V pin (matches Upside Down Labs default wiring)
 *
 * Pipeline
 * ────────
 *  1. FspTimer ISR samples A0 at 256 Hz → circular buffer raw[128]
 *  2. Once 128 samples are ready, copy to vReal[], restart ISR buffer
 *  3. Apply 128-point Hanning-windowed FFT via arduinoFFT
 *  4. Sum FFT magnitudes into 5 EEG bands (Delta–Gamma)
 *  5. Apply StandardScaler (params from arduino_inference.h)
 *  6. Call score() from arduino_inference.h → 3 OvR decision values
 *  7. Softmax → prediction_id + confidence
 *  8. Transmit: "PRED_ID,CONFIDENCE\n"  e.g. "2,0.87\n"
 *
 * SRAM Budget (Renesas RA4M1 — 32,768 bytes total)
 * ─────────────────────────────────────────────────
 *   vReal[128]  float  : 512 bytes
 *   vImag[128]  float  : 512 bytes
 *   raw[128]    int    : 512 bytes  (volatile, ISR circular buffer; int=4B on ARM)
 *   Serial TX/RX bufs  :  64 bytes
 *   Runtime + stack     : ~1 KB
 *   ────────────────────────────────
 *   Total estimate      : ~2.6 KB   (of 32 KB available — ample headroom)
 *
 * On ARM Cortex-M4, const data is stored in flash and accessed via normal
 * pointers — no PROGMEM/pgm_read macros needed (they compile as no-ops).
 *
 * Serial Packet Format
 * ────────────────────
 *  Normal    : "ID,CONF\n"        e.g. "2,0.87\n"
 *  Debug mode: additional "DBG:band=val ..." line before prediction
 *
 * Inference rate : one classification per 128-sample window = 0.5 s
 *
 * Required Library
 * ────────────────
 *  arduinoFFT v1.9.x — install via: Sketch > Include Library > Manage Libraries
 *  (If using v2.x, see comments marked [FFT_V2] below for API differences.)
 *
 * Band–Bin Alignment (128-pt FFT @ 256 Hz → 2 Hz/bin)
 * ────────────────────────────────────────────────────
 *   Band    Hz range   Bins   Frequencies captured
 *   Delta   1–3 Hz     1      bin 1 → 2 Hz
 *   Theta   4–8 Hz     2–4    4, 6, 8 Hz
 *   Alpha   9–13 Hz    5–6    10, 12 Hz
 *   Beta    14–30 Hz   7–15   14, 16, …, 30 Hz
 *   Gamma   31–45 Hz   16–22  32, 34, …, 44 Hz
 *
 * Matches training aggregation in src/train_tinyml.py: mean of Kaggle CSV
 * freq_ columns within each band's Hz range (proxy-trained, scaler-aligned).
 */

#include <FspTimer.h>          // R4 hardware timer (Renesas FSP)
#include <math.h>
#include "arduinoFFT.h"        // install via Library Manager
#include "arduino_inference.h" // auto-generated by src/train_tinyml.py

/* ── Compile-time configuration ──────────────────────────────────────────── */

// Set to 1 to print band power values to Serial each cycle (for calibration).
// Useful for checking that real EEG signals are reaching the ADC correctly.
// Set to 0 for production — avoids adding Serial print overhead.
#define DEBUG_BANDS 0

/* ── Constants ───────────────────────────────────────────────────────────── */

static const uint8_t  SAMPLES     = 128;   // FFT window size (samples per classification)
static const uint16_t SAMPLE_RATE = 256;   // Hz — must match FspTimer setup below
static const uint8_t  N_BANDS     = 5;     // Delta, Theta, Alpha, Beta, Gamma
static const uint8_t  N_CLASSES   = 3;     // calm, relaxed, stressed

// FFT frequency resolution = SAMPLE_RATE / SAMPLES = 256/128 = 2 Hz per bin.
// Bin k covers the frequency range: k×2 Hz to (k+1)×2 Hz.
// Bin 0 = DC (0 Hz) — always excluded from EEG analysis.
// These bin ranges match the band definitions in src/train_tinyml.py exactly.
static const uint8_t BAND_BIN_LO[N_BANDS] = {  1,  2,  5,  7, 16 };  // first bin for each band
static const uint8_t BAND_BIN_HI[N_BANDS] = {  1,  4,  6, 15, 22 };  // last bin for each band
// Pre-computed bin count per band (hi - lo + 1): {1, 3, 2, 9, 7}
// Used to compute the mean magnitude rather than sum, matching Python mean().
static const uint8_t BAND_BIN_N[N_BANDS]  = {  1,  3,  2,  9,  7 };

/* ── SRAM-resident working arrays ────────────────────────────────────────── */

// arduinoFFT v1.9.x API takes double* — on ARM Cortex-M4, double is 8 bytes.
// Using float (4 bytes) via arduinoFFT<float> would halve memory but requires v2.x.
// With 32 KB SRAM on R4, the extra 1 KB is not a concern.
static double vReal[SAMPLES];  // FFT real input / magnitude output
static double vImag[SAMPLES];  // FFT imaginary input (zeroed each window)

// ISR circular buffer — written by FspTimer ISR, read by main loop.
// 'volatile' is REQUIRED here: without it, the compiler may cache these variables
// in CPU registers and never see updates written by the ISR.
static volatile int     raw[SAMPLES];  // 14-bit ADC values from A0 (0–16383)
static volatile uint16_t bufIdx  = 0;  // next write position in raw[]
static volatile bool    bufFull = false;  // true once raw[] has 128 new samples

/* ── arduinoFFT instance ─────────────────────────────────────────────────── */
// The arduinoFFT library does the heavy maths of converting 128 time-domain
// samples into 64 frequency bins (complex FFT → magnitude spectrum).
// [FFT_V2] If you have arduinoFFT v2.x: use ArduinoFFT<float> FFT; instead.
arduinoFFT FFT = arduinoFFT();

/* ── FspTimer: 256 Hz hardware timer interrupt ─────────────────────────── */
//
// WHY a hardware timer? We need ADC sampling at a precise fixed rate.
// The Arduino loop() speed varies depending on how much work each iteration
// does, so we can't use delay() for accurate sampling. FspTimer fires an
// Interrupt Service Routine (ISR) at exactly 256 Hz regardless.
//
// FspTimer is the Arduino R4 abstraction over the Renesas RA4M1 General
// PWM Timer (GPT). We just pass the desired frequency — it handles
// prescaler and compare-match configuration internally.

FspTimer sampleTimer;

// ISR callback — called by FspTimer at 256 Hz.
// Reads one 14-bit ADC value from pin A0 (0–16383) and stores it in the
// circular buffer. After 128 samples, raises bufFull and stops until the
// main loop consumes the buffer.
//
// Timing: fires every ~3.9 ms. analogRead() on R4 Minima takes ~30 µs
// (14-bit SAR @ 48 MHz), leaving ~3870 µs of headroom per ISR period.

void sampleTimerCallback(timer_callback_args_t __attribute__((unused)) *args) {
    if (!bufFull) {
        raw[bufIdx] = analogRead(A0);  // read EEG voltage as 14-bit integer (0–16383)
        bufIdx++;
        if (bufIdx >= SAMPLES) {
            bufFull = true;            // signal main loop: 128 fresh samples are ready
        }
    }
}

void setupSampleTimer() {
    uint8_t timer_type = GPT_TIMER;
    int8_t timer_ch = FspTimer::get_available_timer(timer_type);

    if (timer_ch < 0) {
        Serial.println(F("ERROR: no available GPT timer channel"));
        while (1) {}  // halt — cannot proceed without timer
    }

    sampleTimer.begin(TIMER_MODE_PERIODIC, timer_type, timer_ch,
                      256.0f,   // frequency in Hz
                      0.0f,     // duty cycle (unused for periodic mode)
                      sampleTimerCallback);
    sampleTimer.setup_overflow_irq();
    sampleTimer.open();
    sampleTimer.start();
}

/* ── Softmax helper ──────────────────────────────────────────────────────── */
//
// score() (from arduino_inference.h) returns 3 raw "decision values" — one per
// class. These are not probabilities; they can be any real number. Softmax
// converts them to probabilities that sum to 1.0 so we can report confidence.
//
// The max-subtraction trick (subtract the largest value before calling exp())
// prevents floating-point overflow. Subtracting the max makes all inputs ≤ 0
// before exp(), keeping results in a safe numerical range.
//
// Returns only the probability of the winning class (the confidence score).

static float softmax_confidence(double* scores, int winner) {
    double maxS = scores[0];
    if (scores[1] > maxS) maxS = scores[1];
    if (scores[2] > maxS) maxS = scores[2];

    double expSum = 0.0;
    double expS[N_CLASSES];
    for (uint8_t i = 0; i < N_CLASSES; i++) {
        expS[i]  = exp(scores[i] - maxS);
        expSum  += expS[i];
    }
    return (float)(expS[winner] / expSum);
}

/* ── Setup ───────────────────────────────────────────────────────────────── */

void setup() {
    analogReadResolution(14);  // R4 Minima: use full 14-bit ADC (0–16383)
    Serial.begin(115200);
    Serial.println(F("MindTune-OS Edge BCI v2.0 (R4 Minima, 14-bit ADC)"));
    Serial.println(F("Format: PRED_ID,CONFIDENCE"));
    Serial.println(F("Classes: 0=calm  1=relaxed  2=stressed"));
    Serial.println(F("---"));

    setupSampleTimer();
}

/* ── Main loop ───────────────────────────────────────────────────────────── */

void loop() {
    if (!bufFull) return;   // wait for a full 128-sample window

    /* ── Step 1: Snapshot raw buffer, restart ISR collection ─────────────── */
    // Disable ISR briefly while copying raw[] so the timer callback doesn't
    // write to it mid-copy. At 48 MHz this takes ~100 µs for 128 copies.
    noInterrupts();
    for (uint8_t i = 0; i < SAMPLES; i++) {
        vReal[i] = (double)raw[i];
        vImag[i] = 0.0;
    }
    bufIdx  = 0;
    bufFull = false;
    interrupts();

    /* ── Step 2: 128-point Hanning-windowed FFT ───────────────────────────── */
    // [FFT_V2] v2.x: FFT.windowing(FFT_WIN_TYP_HANN, FFT_FORWARD);
    FFT.Windowing(vReal, SAMPLES, FFT_WIN_TYP_HANN, FFT_FORWARD);
    FFT.Compute(vReal, vImag, SAMPLES, FFT_FORWARD);
    // ComplexToMagnitude overwrites vReal with |magnitude|; vImag becomes 0.
    // [FFT_V2] v2.x: FFT.complexToMagnitude();
    FFT.ComplexToMagnitude(vReal, vImag, SAMPLES);

    /* ── Step 3: Sum magnitudes into 5 EEG bands, compute mean per band ───── */
    // Mean aggregation matches the training script (Python mean of freq_ cols).
    // Bin 0 = DC component — excluded from all bands.
    double band_power[N_BANDS];
    for (uint8_t b = 0; b < N_BANDS; b++) {
        double sum = 0.0;
        for (uint8_t k = BAND_BIN_LO[b]; k <= BAND_BIN_HI[b]; k++) {
            sum += vReal[k];
        }
        band_power[b] = sum / (double)BAND_BIN_N[b];
    }

#if DEBUG_BANDS
    Serial.print(F("DBG:"));
    const char* bnames[] = {"D","Th","Al","Be","G"};
    for (uint8_t b = 0; b < N_BANDS; b++) {
        Serial.print(bnames[b]);
        Serial.print('=');
        Serial.print(band_power[b], 4);
        if (b < N_BANDS - 1) Serial.print(' ');
    }
    Serial.println();
#endif

    /* ── Step 4: Apply StandardScaler (params from arduino_inference.h) ────  */
    // The scaler parameters (mean and scale for each band) were computed by
    // Python's StandardScaler.fit() and embedded into arduino_inference.h.
    // On ARM Cortex-M4, const arrays are in flash and accessed directly —
    // no PROGMEM/pgm_read macros needed (they compile as no-ops on R4).
    // Formula: scaled[i] = (raw_value[i] - mean[i]) / scale[i]
    double scaled[N_BANDS];
    for (uint8_t i = 0; i < N_BANDS; i++) {
        float mean_i  = BAND_SCALER_MEAN[i];
        float scale_i = BAND_SCALER_SCALE[i];
        scaled[i] = (band_power[i] - (double)mean_i) / (double)scale_i;
    }

    /* ── Step 5: Classifier inference ─────────────────────────────────────── */
    double scores[N_CLASSES];
    score(scaled, scores);

    // Argmax → prediction_id
    uint8_t pred_id = 0;
    for (uint8_t i = 1; i < N_CLASSES; i++) {
        if (scores[i] > scores[pred_id]) pred_id = i;
    }

    // Softmax → calibrated confidence for the winning class
    float confidence = softmax_confidence(scores, pred_id);

    /* ── Step 6: Transmit compact serial packet ────────────────────────────── */
    // Format: "PRED_ID,CONFIDENCE\n"  e.g. "2,0.87\n"
    // The Python main_loop (or a host bridge script) parses this.
    Serial.print(pred_id);
    Serial.print(',');
    Serial.println(confidence, 2);
}
